-- Supabase SQL Editor дээр БҮХЛЭН ажиллуулна.

create table if not exists public.exam_settings (
    id integer primary key,
    is_open boolean not null default false,
    updated_at timestamptz not null default now()
);

insert into public.exam_settings (id, is_open)
values (1, false)
on conflict (id) do nothing;

create table if not exists public.exam_results (
    id bigint generated by default as identity primary key,
    exam_date timestamptz not null default now(),
    exam_type text not null,
    surname text not null,
    position text not null,
    score integer not null,
    total_score integer not null,
    percentage numeric(5,1) not null,
    result text not null
);

-- Хэрэв өмнө нь хүснэгт үүсгэсэн бол дээрх CREATE нь зөрчилгүй.
-- Энэ код нь сервер талын Supabase secret/service key ашиглах зориулалттай.
